@baseurl = http://localhost:8080
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDkwMzE5MDAsInVzZXJuYW1lIjoiQXByaWxhamEifQ.OTU61EOb3Zi2yfpQxRtDEREmFVXBmumbNB5cLx4uKJI


POST {{baseurl}}/api/v1/signup
Content-Type: application/json

{
  "name": "April",
  "username": "April Aneh",
  "email": "april@example.com",
  "password": "password",
  "address": "123 Main St",
  "phoneNumber": "123-456-7890",
  "memberStatus": "gold",
  "reviews": [],
  "bookingHistory": []
}

###
GET {{baseurl}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


###
PUT http://localhost:8080/api/users/1
Content-Type: application/json


{
    "name": "Indra",
    "username": "indraaja",
    "email": "indra@example.com",
    "password": "password123",
    "address": "123 Main Street",
    "phone_number": "+1234567890",
    "member_status": "gold",
    "reviews": [],
    "booking_history": []
}

###
DELETE http://localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


###
POST http://localhost:8080/api/review
Content-Type: application/json

{
    "user_id": 1,
    "room_id": 3,
    "rating": 3,
    "comment": "lumayan bagus fasilitasnya",
    "user": {
        "name": "John Doe",
        "email": "john.doe@example.com",
        "password": "password123"
    },
    "room": {

        "room_number": "100",
        "type": "Premium",
        "price": 120000
    }
}

###
GET {{baseurl}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

###
DELETE   http://localhost:8080/api/v1/rooms/5
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    //"email": "april@example.com",
    "username": "Aprilaja",
    "password": "password"
}